package day7Test;

import com.AoC.Diego.day7.TachyonSolver;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class TachyonSolverTest {

    private static final String EXAMPLE = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";

    @Test
    void testPart1Example() {

        TachyonSolver solver = new TachyonSolver(EXAMPLE);

        assertEquals(21, solver.countSplits());
    }

    @Test
    void testPart2Example() {

        TachyonSolver solver = new TachyonSolver(EXAMPLE);

        assertEquals(40, solver.countTimelines());
    }
}