package com.AoC.Diego.day7;

public class Mainday7 {

    public static void main(String[] args) {

        String input = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";

        TachyonSolver solver = new TachyonSolver(input);

        System.out.println("===== Ejemplo =====");
        System.out.println("Parte 1: " + solver.countSplits());
        System.out.println("Parte 2: " + solver.countTimelines());
    }
}